### PR TITLE
Use update_bundle.yaml reusable workflow

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**

### CODE REVIEW

**Comment by taurus-forever** [comment]
@dragomirp can the error `juju.errors.JujuError: ['subordinate application must be deployed without constraints']` be addressed quickly here?

**Comment by dragomirp** [comment]
> @dragomirp can the error `juju.errors.JujuError: ['subordinate application must be deployed without constraints']` be addressed quickly here?
I'm not sure. I should be fixing it this pulse, but I can't promise it will be fast or soon. I propose merging this PR as is.

**Review by dragomirp — APPROVED** [review]

**Review by marceloneppel — APPROVED** [review]
Like Dragomir, I propose to merge this PR as is, as the errors are related to another issue.

**Comment by dragomirp** [comment]
> > @dragomirp can the error `juju.errors.JujuError: ['subordinate application must be deployed without constraints']` be addressed quickly here?
> > I'm not sure.
Turned out to be a one line change.

**Review by taurus-forever — APPROVED** [review]

**Pull request merged**
