### PR TITLE
Cancel CI that is not the latest commit on a branch

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**
Ported from https://github.com/canonical/mysql-operator/pull/134

### CODE REVIEW

**Comment by dragomirp** [comment]
Since postgresql VM charm's edge channel got overwritten, integration tests aren't going to pass. @taurus-forever @marceloneppel How should we proceed with this PR?

**Comment by taurus-forever** [comment]
> How should we proceed with this PR?

1) to fix: only the option is to upgrade postgresql into jammy
2) to hide the problem: If we really need it to work urgently, we can call the CLI directly from the tests like [here](https://github.com/canonical/pgbouncer-operator/blob/dpe-1219-subordination/tests/integration/helpers/helpers.py#L320), at least temporarily (c) Dragomir.

**Review by taurus-forever — APPROVED** [review]

**Review by marceloneppel — APPROVED** [review]
Great! Thanks Carl! I triggered the CI again as PostgreSQL was updated to jammy.

**Comment by marceloneppel** [comment]
> @marceloneppel Is this PR okay to merge with some of the integration tests failing?

It's ok Carl! I'm opening another PR to fix those issues. Thanks for the PR!

**Pull request merged**
